### ISSUE TITLE
Counter only counts 2/3 ralts in hordes...

### ISSUE THREAD

**Issue by Xross98** [ssjshields/pokemmo-archetype#19]
Doing Ralts hordes and it only counts 2 out of the 3, havent tested any 5 hordes yet since I'm pre badge 5 in sinnoh and don't know where any are located.
I assume the way it counts in based on what's on screen but the issue doesn't seem to occur with the Bibarel hordes despite the 3rd sprite also being cut off, maybe I'm wrong though. :p
![ScreenShot_20220910074103](https://user-images.githubusercontent.com/106489040/189472531-a35a1a62-cfd4-4320-94ea-290eb0f092b5.png)
![ScreenShot_20220910074125](https://user-images.githubusercontent.com/106489040/189472533-d5bdfeda-450d-4ba4-b7a2-ad9d15b19ffa.png)

**Comment by ssjshields** [comment]
@Xross98 Thanks for the report. We are working on another build that further addresses horde count logic.

What version is your `Counter.exe`?

**Comment by ssjshields** [comment]
@Xross98 
As per https://github.com/ssjshields/pokemmo-archetype/tree/counter#prerequisites please disable your battle backgrounds.

Thank you.

Open another issue if this continues to occur.
